"""Add icons for store and item

Revision ID: 1cf6928e1d09
Revises: 08e336c9d6dd
Create Date: 2024-03-26 18:40:18.641638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf6928e1d09'
down_revision: Union[str, None] = '08e336c9d6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_images',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_id'), 'item_images', ['id'], unique=True)
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    op.add_column('items', sa.Column('icon', sa.String(length=100), nullable=True))
    op.add_column('stores', sa.Column('icon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'icon')
    op.drop_column('items', 'icon')
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.drop_index(op.f('ix_item_images_id'), table_name='item_images')
    op.drop_table('item_images')
    # ### end Alembic commands ###
