"""Add Order Columns

Revision ID: 206390466571
Revises: 6a3e1e3712d9
Create Date: 2024-05-27 17:59:53.710156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206390466571'
down_revision: Union[str, None] = '6a3e1e3712d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(length=200), nullable=False))
    op.add_column('orders', sa.Column('note', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
