"""Add report images

Revision ID: 97e3297e8de6
Revises: 80b4c7b658cd
Create Date: 2024-04-01 11:47:52.251872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e3297e8de6'
down_revision: Union[str, None] = '80b4c7b658cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_report_images',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['user_reports.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_report_images_id'), 'user_report_images', ['id'], unique=True)
    op.create_table('item_report_images',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['item_reports.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_report_images_id'), 'item_report_images', ['id'], unique=True)
    op.add_column('item_reports', sa.Column('reason', sa.String(length=500), nullable=False))
    op.add_column('user_reports', sa.Column('reason', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_reports', 'reason')
    op.drop_column('item_reports', 'reason')
    op.drop_index(op.f('ix_item_report_images_id'), table_name='item_report_images')
    op.drop_table('item_report_images')
    op.drop_index(op.f('ix_user_report_images_id'), table_name='user_report_images')
    op.drop_table('user_report_images')
    # ### end Alembic commands ###
